client_id: 42249290
auth_token: ""
anonymous: true
device_id: anonymous-device
secret_key: 6uQTpfFgW2iv8Nd09MaLmKjSgF1CCC9f
server:
    address: 127.0.0.1:8080
    protocol: tcp
log:
    level: debug
    format: text
    output: file
    file: ~/logs/ListenClient.log
