client_id: 90521524
auth_token: ""
anonymous: true
device_id: anonymous-device
secret_key: ew2HUdwOKIRJU0hr5OFkufinh97O69Ey
server:
    address: http://127.0.0.1:9000
    protocol: httppoll
log:
    level: ""
    format: ""
    output: ""
    file: /tmp/tunnox-client.log
