client_id: 10647721
# auth_token: ""  # 仅用于注册客户端认证，匿名模式下不需要
anonymous: true
device_id: anonymous-device
secret_key: 30sRDc4lob6O3cq0vhJ2wS3EEbF9xkWT
server:
    address: 127.0.0.1:8000
    protocol: tcp
log:
    level: "info"    # 日志级别: debug, info, warn, error, fatal, panic
    format: "text"   # 日志格式: text, json
    output: "file"   # 输出位置: stdout, stderr, file
    file: /tmp/tunnox-target-client.log
