client_id: 10647721
auth_token: ""
anonymous: true
device_id: anonymous-device
secret_key: 30sRDc4lob6O3cq0vhJ2wS3EEbF9xkWT
server:
    address: 127.0.0.1:8000
    protocol: tcp
log:
    level: ""
    format: ""
    output: ""
    file: /tmp/tunnox-target-client.log
