client_id: 56512552
auth_token: ""
anonymous: true
device_id: anonymous-device
secret_key: vAeGPBINSWCkP9TboqdGFxCtPI9X9Mrb
server:
    address: http://127.0.0.1:9000
    protocol: httppoll
log:
    level: ""
    format: ""
    output: ""
    file: /tmp/tunnox-target-client.log
